# Generated by Django 3.1.2 on 2020-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_getter', '0002_auto_20201027_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryfile',
            name='file',
            field=models.FileField(upload_to='uploads/binary/'),
        ),
    ]
