# Generated by Django 3.1.2 on 2020-10-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_getter', '0004_auto_20201028_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/images/')),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_getter.binaryfile')),
            ],
            options={
                'verbose_name': 'Img file',
                'verbose_name_plural': 'Img files',
            },
        ),
    ]
