# Generated by Django 3.0.8 on 2020-10-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_pay', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Type',
        ),
    ]
