# Generated by Django 3.0.8 on 2020-10-31 20:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_pay', '0002_auto_20201031_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='example',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='C:\\fpi\\mysite\\static/files'), upload_to='', verbose_name='Образец'),
            preserve_default=False,
        ),
    ]
