# Generated by Django 3.0.8 on 2020-10-31 21:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_pay', '0003_type_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название документа')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\fpi\\mysite\\static/files'), upload_to='', verbose_name='Документ')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='log_pay.Type', verbose_name='Класс документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
