# Generated by Django 3.0.8 on 2020-10-31 23:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_pay', '0004_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='adress',
            field=models.CharField(default=1, max_length=128, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Широта, °'),
        ),
        migrations.AddField(
            model_name='doc',
            name='long',
            field=models.FloatField(default=0, verbose_name='Долгота, °'),
        ),
        migrations.AddField(
            model_name='doc',
            name='nomber',
            field=models.CharField(default=1, max_length=128, verbose_name='Номер документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='owner',
            field=models.CharField(default=1, max_length=128, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.CharField(max_length=580, verbose_name='Ссылка документа'),
        ),
        migrations.AlterField(
            model_name='type',
            name='example',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:/static/files/'), upload_to='', verbose_name='Образец'),
        ),
    ]
